CREATE TABLE IF NOT EXISTS `#__ofrs_offer` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`asset_id` INT(10) unsigned NOT NULL DEFAULT 0 COMMENT 'FK to the #__assets table.',
	`ad_network_id` INT NOT NULL DEFAULT 0,
	`affiliate_access` CHAR(1) NOT NULL DEFAULT '',
	`create_date_at_net` DATE NULL DEFAULT '0000-00-00',
	`description` TEXT NOT NULL,
	`expire_date_at_net` DATE NULL DEFAULT '0000-00-00',
	`geo_targeting` VARCHAR(2048) NULL DEFAULT '',
	`name` VARCHAR(255) NOT NULL DEFAULT '',
	`offer_id` INT NULL DEFAULT 0,
	`offer_id_at_network` VARCHAR(10) NOT NULL DEFAULT '',
	`payouts` VARCHAR(2048) NULL DEFAULT '',
	`preview_url` VARCHAR(2048) NOT NULL DEFAULT '',
	`verticals` VARCHAR(2048) NULL DEFAULT '',
	`params` text NOT NULL,
	`published` TINYINT(3) NOT NULL DEFAULT 1,
	`created_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`modified_by` INT(10) unsigned NOT NULL DEFAULT 0,
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`modified` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`checked_out` int(11) unsigned NOT NULL DEFAULT 0,
	`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`version` INT(10) unsigned NOT NULL DEFAULT 1,
	`hits` INT(10) unsigned NOT NULL DEFAULT 0,
	`ordering` INT(11) NOT NULL DEFAULT 0,
	PRIMARY KEY  (`id`),
	KEY `idx_checkout` (`checked_out`),
	KEY `idx_createdby` (`created_by`),
	KEY `idx_modifiedby` (`modified_by`),
	KEY `idx_state` (`published`),
	KEY `idx_name` (`name`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 DEFAULT COLLATE=utf8_general_ci;
